In [ ]:
# อัปเดตและติดตั้ง PostgreSQL พร้อม PostGIS สำหรับทำ Geospatial
!apt-get -y -qq update
!apt-get -y -qq install postgresql postgresql-contrib postgis

# สตาร์ท service
!service postgresql start

# ตั้งค่า User และสร้าง Database
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"
!sudo -u postgres psql -U postgres -c "CREATE DATABASE chicago_crime;"

# เปิดการใช้งาน PostGIS
!sudo -u postgres psql -d chicago_crime -c "CREATE EXTENSION IF NOT EXISTS postgis;"

# ติดตั้ง Library ของ Python
!pip install -q psycopg2-binary sqlalchemy pandas requests

In [ ]:
# import libralies & connect DB
import pandas as pd
from sqlalchemy import create_engine, text
import requests
import io

# สร้าง connection ไปยัง postgresql on colab
db_url = "postgresql://postgres:postgres@localhost:5432/chicago_crime"
engine = create_engine(db_url)
print("Database Connection Setup Complete")

Database Connection Setup Complete

### Task1: Data ingestion นำเข้าข้อมูล

Logic Task 1: Data Ingestion
- นำเข้าข้อมูล CSV เข้า Postgresql
วิธีที่ใช้ก็คือ ดึงข้อมูลผ่าน API เพราะไม่ต้องโหลดไฟล์ CSV มาเก็บในเครื่อง เพราะไฟล์มันใหญ่โหลดนาน และใช้ฟีเจอร์ของ Socrata API ในการคัดกรองข้อมูล เพื่อให้ได้ข้อมูล Sample 100,000 แถวที่เป็นของปี 2024-ปัจจุบัน ช่วยประหยัดเวลาดาวน์โหลดและลดการใช้ Memory ของระบบ

- ปรับชื่อคอลัมน์เป็น snake_case (เช่น case_number) ทั้งหมด เวลาเขียน SQL จะได้ไม่ต้อง error และแปลงข้อมูลวันที่ให้เป็น DateTime เพื่อให้ Database เข้าใจและใช้คำนวณเวลาย้อนหลังได้

- นำเข้าฐานข้อมูล โดยใช้ฟังก์ชันของ pandas โยนข้อมูลใส่ PostgreSQL รวดเดียวผ่าน SQLAlchemy

In [ ]:
# ใช้ข้อมูล 100,000 rows (2024-present)
api_url = "https://data.cityofchicago.org/resource/ijzp-q8t2.csv?$limit=100000&$where=year>=2024"
response = requests.get(api_url)
df = pd.read_csv(io.StringIO(response.text))

In [ ]:
# ทำการ clean data และ แปลง format columns
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df['date'] = pd.to_datetime(df['date'])
df

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,14121258,JK162147,2026-02-25 00:00:00,054XX S WOLCOTT AVE,0420,BATTERY,AGGRAVATED - KNIFE / CUTTING INSTRUMENT,RESIDENCE,False,True,...,16,61.0,04B,1164611.0,1868625.0,2026,2026-03-04T15:45:19.000,41.795117,-87.671904,"\n, \n(41.795116965, -87.671903764)"
1,14121831,JK162814,2026-02-25 00:00:00,048XX S LOOMIS BLVD,0630,BURGLARY,ATTEMPT FORCIBLE ENTRY,RESIDENCE,False,False,...,20,61.0,05,1167816.0,1872624.0,2026,2026-03-04T15:45:19.000,41.806022,-87.660036,"\n, \n(41.806022407, -87.660036124)"
2,14122854,JK164159,2026-02-25 00:00:00,0000X S WACKER DR,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,42,32.0,11,1173943.0,1900083.0,2026,2026-03-04T15:45:19.000,41.881238,-87.636748,"\n, \n(41.8812382, -87.636747795)"
3,14121527,JK162427,2026-02-25 00:00:00,063XX N SACRAMENTO AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,50,2.0,08A,1155197.0,1941892.0,2026,2026-03-04T15:45:19.000,41.996362,-87.704456,"\n, \n(41.996362017, -87.704455913)"
4,14121079,JK162033,2026-02-25 00:00:00,067XX N GREENVIEW AVE,0460,BATTERY,SIMPLE,STREET,False,False,...,49,1.0,08B,1165051.0,1944766.0,2026,2026-03-04T15:45:19.000,42.004044,-87.668125,"\n, \n(42.004044032, -87.668125318)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,13963581,JJ410559,2025-09-11 14:23:00,102XX S INDIANAPOLIS AVE,5111,OTHER OFFENSE,GUN OFFENDER - ANNUAL REGISTRATION,STREET,True,False,...,10,52.0,26,1203263.0,1837592.0,2025,2025-11-02T15:41:09.000,41.709057,-87.531230,"\n, \n(41.709057114, -87.531230186)"
99996,13963777,JJ410604,2025-09-11 14:20:00,002XX W ADAMS ST,0320,ROBBERY,STRONG ARM - NO WEAPON,STREET,True,False,...,42,32.0,03,1174663.0,1899413.0,2025,2025-11-02T15:41:09.000,41.879384,-87.634124,"\n, \n(41.879383612, -87.634124064)"
99997,13963965,JJ410602,2025-09-11 14:20:00,036XX W 57TH ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,23,62.0,08B,1153013.0,1866567.0,2025,2025-11-02T15:41:09.000,41.789707,-87.714488,"\n, \n(41.789706514, -87.714488424)"
99998,13973261,JJ421762,2025-09-11 14:18:00,022XX S MICHIGAN AVE,0890,THEFT,FROM BUILDING,COMMERCIAL / BUSINESS OFFICE,False,False,...,3,33.0,06,1177562.0,1889470.0,2025,2025-11-02T15:41:09.000,41.852034,-87.623781,"\n, \n(41.852034102, -87.623781281)"
99999,13963627,JJ410726,2025-09-11 14:15:00,001XX W LAKE ST,0870,THEFT,POCKET-PICKING,SIDEWALK,False,False,...,42,32.0,06,1175401.0,1901736.0,2025,2025-11-02T15:41:09.000,41.885742,-87.631345,"\n, \n(41.885741529, -87.631344503)"

In [ ]:
# ingesting to Postgresql
with engine.begin() as conn:
    df.to_sql('crime_data', con=conn, if_exists='replace', index=False)

print(f"Task 1 Complete: Successfully loaded {len(df)} rows into 'crime_data' table.")

Task 1 Complete: Successfully loaded 100000 rows into 'crime_data' table.

### Task 2: Schema design
- สร้างสารบัญข้อมูล Index: การกวาดหาข้อมูลนับแสนบรรทัดตรงๆ จะทำให้ระบบช้ามาก เลยสร้าง Index ให้ Column "วันที่" และ "เขต (District)" ช่วยให้ระบบกระโดดไปดึงข้อมูลช่วงเวลาหรือพื้นที่ที่ต้องการได้ทันที

- เตรียมข้อมูลพิกัดแผนที่ Geospatial Setup: ฐานข้อมูลทั่วไปมองตัวเลข Latitude/Longitude เป็นแค่ตัวอักษร ทำให้คำนวณระยะทางหรือพื้นที่ทับซ้อนไม่ได้
เลยใช้ PostGIS แปลงตัวเลขให้เป็น "จุดพิกัดบนแผนที่ (Geometry)"  และทำสารบัญแผนที่ (GiST Index) เตรียมไว้ เพื่อส่งต่อให้โมเดล AI วิเคราะห์เชิงพื้นที่ต่อ

In [ ]:
schema_sql = """
-- 1. สร้าง Time-series Index (B-Tree)
CREATE INDEX IF NOT EXISTS idx_crime_date ON crime_data (date DESC);

-- 2. สร้าง Index สำหรับ Filter ที่ใช้บ่อย (Type, District)
CREATE INDEX IF NOT EXISTS idx_crime_type_district ON crime_data (primary_type, district);

-- 3. เพิ่มคอลัมน์ Geometry สำหรับ PostGIS (SRID 4326)
ALTER TABLE crime_data ADD COLUMN IF NOT EXISTS geom GEOMETRY(Point, 4326);

-- 4. แปลงข้อมูล Latitude/Longitude ให้อยู่ในรูป Geometry Object
UPDATE crime_data
SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

-- 5. สร้าง Geospatial Index (GiST)
CREATE INDEX IF NOT EXISTS idx_crime_geom ON crime_data USING GIST (geom);
"""

with engine.begin() as conn:
    conn.execute(text(schema_sql))

print("✅ Task 2 Complete: Schema optimized and geospatial column updated.")

✅ Task 2 Complete: Schema optimized and geospatial column updated.

In [ ]:
schema_sql

'\n-- 1. สร้าง Time-series Index (B-Tree)\nCREATE INDEX IF NOT EXISTS idx_crime_date ON crime_data (date DESC);\n\n-- 2. สร้าง Index สำหรับ Filter ที่ใช้บ่อย (Type, District)\nCREATE INDEX IF NOT EXISTS idx_crime_type_district ON crime_data (primary_type, district);\n\n-- 3. เพิ่มคอลัมน์ Geometry สำหรับ PostGIS (SRID 4326)\nALTER TABLE crime_data ADD COLUMN IF NOT EXISTS geom GEOMETRY(Point, 4326);\n\n-- 4. แปลงข้อมูล Latitude/Longitude ให้อยู่ในรูป Geometry Object\nUPDATE crime_data \nSET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)\nWHERE latitude IS NOT NULL AND longitude IS NOT NULL;\n\n-- 5. สร้าง Geospatial Index (GiST)\nCREATE INDEX IF NOT EXISTS idx_crime_geom ON crime_data USING GIST (geom);\n'

### Task 3: Complex Querying
- วันที่ไม่มีคดีเกิดขึ้น จะไม่มีข้อมูลในระบบ ถ้าจับมาหาค่าเฉลี่ยตรงๆ ตัวหารจะหายไป (เช่น หาร 5 วัน แทนที่จะหาร 7 วัน) ทำให้ค่าเฉลี่ยเพี้ยน
สั่ง SQL ให้สร้างวันที่ให้ครบทุกวัน และครบทุกเขต (District)

- เติมศูนย์: วันไหนไม่มีคดี ให้บังคับเติมเลข "0" ลงไป

In [31]:
query = """
WITH dataset_bounds AS (
    SELECT MAX(date::date) as max_date FROM crime_data
),
target_dates AS (
    SELECT generate_series(
        (SELECT max_date FROM dataset_bounds) - INTERVAL '36 days',
        (SELECT max_date FROM dataset_bounds),
        INTERVAL '1 day'
    )::date AS report_date
),
districts AS (
    SELECT DISTINCT district FROM crime_data WHERE district IS NOT NULL
),
daily_thefts AS (
    SELECT date::date AS theft_date, district, COUNT(*) AS theft_count
    FROM crime_data
    WHERE primary_type = 'THEFT'
    GROUP BY date::date, district
),
filled_data AS (
    SELECT t.report_date, d.district, COALESCE(dt.theft_count, 0) AS daily_count
    FROM target_dates t
    CROSS JOIN districts d
    LEFT JOIN daily_thefts dt ON t.report_date = dt.theft_date AND d.district = dt.district
),
rolling_calc AS (
    SELECT
        report_date, district, daily_count,
        ROUND(AVG(daily_count) OVER (
            PARTITION BY district ORDER BY report_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ), 2) AS rolling_avg_7d
    FROM filled_data
)
SELECT * FROM rolling_calc
WHERE report_date >= (SELECT max_date FROM dataset_bounds) - INTERVAL '30 days'
ORDER BY district, report_date DESC;
"""

with engine.connect() as conn:
    rolling_avg_df = pd.read_sql(text(query), con=conn)

print("Task 3 Complete: Result preview Top 15 rows:")
display(rolling_avg_df.head(15))

Task 3 Complete: Result preview Top 15 rows:

   report_date  district  daily_count  rolling_avg_7d
0   2026-02-25         1            0            7.43
1   2026-02-24         1            9           10.29
2   2026-02-23         1            9           10.14
3   2026-02-22         1            3            9.29
4   2026-02-21         1           11           10.29
5   2026-02-20         1           10           10.43
6   2026-02-19         1           10           10.00
7   2026-02-18         1           20            9.86
8   2026-02-17         1            8            8.86
9   2026-02-16         1            3            9.71
10  2026-02-15         1           10           10.43
11  2026-02-14         1           12           10.14
12  2026-02-13         1            7           10.71
13  2026-02-12         1            9           11.00
14  2026-02-11         1           13           11.71

### Task 4: Checking Data Integrity

 - ข้อมูลบางคดีไม่มีพิกัด หากนำไปพล็อตแผนที่หรือเทรน Geospatial AI โมเดลจะ Error ทันที

 - หลังจากที่เช็ค % ที่หายไป เลือกวิธีจัดการ 2 แบบ:
1. เติมค่า (Spatial Imputation): หากไม่อยากเสียข้อมูล ให้เอา "พิกัดจุดกึ่งกลาง" ของเขตนั้นๆ มาเติมแทน

2. ตัดทิ้ง (Exclusion): หากข้อมูลหายไปน้อยมาก (เช่น < 2%) ให้ลบทิ้งไปเลย เป็นวิธีที่คลีนที่สุดและไม่สร้าง Noise ให้โมเดล AI วิเคราะห์เชิงพื้นที่ต่อไปได้

In [ ]:
total_rows = len(df)
print(f"Total Rows: {total_rows} ")

Total Rows: 100000

In [ ]:
missing_locations = df[(df['latitude'].isnull()) | (df['longitude'].isnull())]
missing_locations_total = len(missing_locations)
print(f"Missing locations total: {missing_locations_total}")

Missing locations total: 75

In [ ]:
missing_locations_percentage = (missing_locations_total / total_rows) * 100
print(f"Missing Values = {missing_locations_percentage:.2f}%")

Missing Values = 0.07%